package it.movioletto.GravityBall3;

/**
 * tutti i tipi di immagine
 * @author Movioletto
 */
public enum Tipo
{
	PALLA, MURO, MUROV, BORDO1, BORDO2, BONUS, SOLDO, TESTO, TESTO70, EASY, EASYC, MEDIUM, MEDIUMC, HARD, HARDC, BONUSM, BONUSMC, BONUSPM, BONUSPMC, BONUSP, BONUSPC, SFONDOPOPUP, MUSICA, MUSICAC, POPUP400X250, POPUP750X310, TOTALE, FRECCIASU40, FRECCIADESTRA40, FRECCIAGIU40, FRECCIASINISTRA40, FRECCIASU, FRECCIADESTRA, FRECCIAGIU, FRECCIASINISTRA, PALLA2, BG, ISTRUZIONI1, ISTRUZIONI2, TESTO100, TESTO140, TESTO150, PAUSA, TOUCH, TOUCHC, ACCEL, ACCELC, MIX, MIXC, EASYH, EASYHC, MEDIUMH, MEDIUMHC, HARDH, HARDHC, TOUCHSG, TOUCHSD, MIXSG, MIXSD
}
